"""empty message

Revision ID: 1ea6380ec29f
Revises: 935ba8738399
Create Date: 2025-06-08 16:11:08.323589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea6380ec29f'
down_revision = '935ba8738399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.drop_column('round')

    # ### end Alembic commands ###
