"""empty message

Revision ID: 4f24f8c6d7bc
Revises: d25392b78eeb
Create Date: 2025-06-04 19:54:05.639132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f24f8c6d7bc'
down_revision = 'd25392b78eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('voice_emotion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('face_emotion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('advanced_text', sa.Text(), nullable=True))
        batch_op.alter_column('speaker_text',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('emotion')
        batch_op.drop_column('gaze_bearing')
        batch_op.drop_column('gaze_strength')
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('gaze_strength', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gaze_bearing', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('emotion', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('speaker_text',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('advanced_text')
        batch_op.drop_column('face_emotion')
        batch_op.drop_column('voice_emotion')
        batch_op.drop_column('time')

    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
