"""empty message

Revision ID: 5e52b2d1fa91
Revises: d1c115007945
Create Date: 2025-05-29 15:48:33.745956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e52b2d1fa91'
down_revision = 'd1c115007945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_interviewer_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('speaker_text', sa.Text(), nullable=False))
        batch_op.drop_column('speaker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('speaker_text')
        batch_op.drop_column('ai_interviewer_text')

    # ### end Alembic commands ###
