"""empty message

Revision ID: 88fe2be7b24c
Revises: c1eaeded0c55
Create Date: 2025-06-05 18:37:29.336213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fe2be7b24c'
down_revision = 'c1eaeded0c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_bearing_degrees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_gaze_strength', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_avg_pitch', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_speech_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_pause_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_pause_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_pause_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audio_words_per_minute', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.drop_column('audio_words_per_minute')
        batch_op.drop_column('audio_pause_count')
        batch_op.drop_column('audio_pause_ratio')
        batch_op.drop_column('audio_pause_time')
        batch_op.drop_column('audio_speech_time')
        batch_op.drop_column('audio_avg_pitch')
        batch_op.drop_column('average_gaze_strength')
        batch_op.drop_column('average_bearing_degrees')

    # ### end Alembic commands ###
