"""empty message

Revision ID: 935ba8738399
Revises: 88fe2be7b24c
Create Date: 2025-06-05 21:33:38.601337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '935ba8738399'
down_revision = '88fe2be7b24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.alter_column('ai_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('speaker_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.alter_column('speaker_time',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('ai_time',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
