"""empty message

Revision ID: 99b0a27e73bc
Revises: 4f24f8c6d7bc
Create Date: 2025-06-04 19:56:59.218968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99b0a27e73bc'
down_revision = '4f24f8c6d7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('speaker_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('speaker_time')
        batch_op.drop_column('ai_time')

    # ### end Alembic commands ###
