"""empty message

Revision ID: 9b4e6dd0bc4b
Revises: f2af6aaaa61f
Create Date: 2025-05-29 16:04:56.577873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4e6dd0bc4b'
down_revision = 'f2af6aaaa61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interviewer_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.drop_column('interviewer_name')

    # ### end Alembic commands ###
