"""empty message

Revision ID: c1eaeded0c55
Revises: 99b0a27e73bc
Create Date: 2025-06-04 20:25:23.013367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1eaeded0c55'
down_revision = '99b0a27e73bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.alter_column('face_emotion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_turn', schema=None) as batch_op:
        batch_op.alter_column('face_emotion',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
