"""empty message

Revision ID: d1c115007945
Revises: da2dc1d94273
Create Date: 2025-05-28 21:05:23.703064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c115007945'
down_revision = 'da2dc1d94273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('current_interview_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_turn',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=200), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('gaze_bearing', sa.Float(), nullable=True),
    sa.Column('gaze_strength', sa.Float(), nullable=True),
    sa.Column('is_focused', sa.Boolean(), nullable=True),
    sa.Column('speaker', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_turn')
    op.drop_table('interview_record')
    # ### end Alembic commands ###
