"""empty message

Revision ID: d25392b78eeb
Revises: 9b4e6dd0bc4b
Create Date: 2025-05-29 16:07:47.430292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25392b78eeb'
down_revision = '9b4e6dd0bc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_style', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.drop_column('interview_style')

    # ### end Alembic commands ###
