"""empty message

Revision ID: f2af6aaaa61f
Revises: 5e52b2d1fa91
Create Date: 2025-05-29 15:57:47.748307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2af6aaaa61f'
down_revision = '5e52b2d1fa91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spend_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_record', schema=None) as batch_op:
        batch_op.drop_column('spend_time')

    # ### end Alembic commands ###
